let canvas = document.getElementById("main-canvas");
var pageWidth, pageHeight;
let ctx = canvas.getContext('2d');
let curHighlight = [];
let closed = [];
let nulls = [];
let nullProbability = 0.1;
let mousex, mousey;
let togglePath = 0;
let diagnolsOn = true;
let showingPath = false;
let blinking = false;
let blinkingColor = "white";
let lastNode = [];
let start = [];
let target = [];
let clicks = 0;
let graph = [];
let amtH = 30;
let amtV = 20;
let defColor = "blue";
let pathColor = "white";
let startColor = "green";
let targetColor = "red";
let highlightColor = "yellow";
let nullColor = "black";